// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using service_data.Models;

#nullable disable

namespace service_data.Migrations
{
    [DbContext(typeof(ServiceAppDbContext))]
    [Migration("20240513195054_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("service_data.Models.EntityModels.Admin", b =>
                {
                    b.Property<Guid>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Admin_user_idUser_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Admin_id");

                    b.HasIndex("Admin_user_idUser_id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Costumer", b =>
                {
                    b.Property<Guid>("Costumer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Costumer_user_idUser_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Costumer_id");

                    b.HasIndex("Costumer_user_idUser_id");

                    b.ToTable("Costumer");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Handyman", b =>
                {
                    b.Property<Guid>("Handyman_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Handyman_user_idUser_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Handyman_id");

                    b.HasIndex("Handyman_user_idUser_id");

                    b.ToTable("Handyman");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.Property<Guid>("Message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Costumer_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("Handyman_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Ticket_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Message_id");

                    b.HasIndex("Costumer_id");

                    b.HasIndex("Handyman_id");

                    b.HasIndex("Ticket_id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Property<Guid>("Ticket_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Costumer_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("HandymenHandyman_id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("statusEnum")
                        .HasColumnType("int");

                    b.HasKey("Ticket_id");

                    b.HasIndex("Costumer_id");

                    b.HasIndex("HandymenHandyman_id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.Property<Guid>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("User_id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Admin", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Admin_user_id")
                        .WithMany()
                        .HasForeignKey("Admin_user_idUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin_user_id");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Costumer", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Costumer_user_id")
                        .WithMany()
                        .HasForeignKey("Costumer_user_idUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer_user_id");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Handyman", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Handyman_user_id")
                        .WithMany()
                        .HasForeignKey("Handyman_user_idUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handyman_user_id");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.Costumer", "Costumer")
                        .WithMany("Messages")
                        .HasForeignKey("Costumer_id");

                    b.HasOne("service_data.Models.EntityModels.Handyman", "Handyman")
                        .WithMany("Messages")
                        .HasForeignKey("Handyman_id");

                    b.HasOne("service_data.Models.EntityModels.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("Ticket_id");

                    b.Navigation("Costumer");

                    b.Navigation("Handyman");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.Costumer", "Costumer")
                        .WithMany("Tickets")
                        .HasForeignKey("Costumer_id");

                    b.HasOne("service_data.Models.EntityModels.Handyman", "Handymen")
                        .WithMany("Tickets")
                        .HasForeignKey("HandymenHandyman_id");

                    b.Navigation("Costumer");

                    b.Navigation("Handymen");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Costumer", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Handyman", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
