// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using service_data.Models;

#nullable disable

namespace service_data.Migrations
{
    [DbContext(typeof(ServiceAppDbContext))]
    [Migration("20240330082421_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.Property<Guid>("Message_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SenderUser_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Ticket_Id")
                        .HasColumnType("char(36)");

                    b.HasKey("Message_Id");

                    b.HasIndex("SenderUser_Id");

                    b.HasIndex("Ticket_Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Property<Guid>("Ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CostumerUser_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("HandymanUser_Id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("statusEnum")
                        .HasColumnType("int");

                    b.HasKey("Ticket_Id");

                    b.HasIndex("CostumerUser_Id");

                    b.HasIndex("HandymanUser_Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("Ticket_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("User_Id");

                    b.HasIndex("Ticket_Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUser_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("service_data.Models.EntityModels.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("Ticket_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Costumer")
                        .WithMany()
                        .HasForeignKey("CostumerUser_Id");

                    b.HasOne("service_data.Models.EntityModels.User", "Handyman")
                        .WithMany()
                        .HasForeignKey("HandymanUser_Id");

                    b.Navigation("Costumer");

                    b.Navigation("Handyman");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.Ticket", null)
                        .WithMany("Users")
                        .HasForeignKey("Ticket_Id");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
