// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using service_data.Models;

#nullable disable

namespace service_data.Migrations
{
    [DbContext(typeof(ServiceAppDbContext))]
    partial class ServiceAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TicketUser", b =>
                {
                    b.Property<Guid>("UsersTicket_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersUser_id")
                        .HasColumnType("char(36)");

                    b.HasKey("UsersTicket_id", "UsersUser_id");

                    b.HasIndex("UsersUser_id");

                    b.ToTable("TicketUser");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.Property<Guid>("Message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SenderUser_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Ticket_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Message_id");

                    b.HasIndex("SenderUser_id");

                    b.HasIndex("Ticket_id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Property<Guid>("Ticket_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("statusEnum")
                        .HasColumnType("int");

                    b.HasKey("Ticket_id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.Property<Guid>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("User_id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TicketUser", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.Ticket", null)
                        .WithMany()
                        .HasForeignKey("UsersTicket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("service_data.Models.EntityModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Message", b =>
                {
                    b.HasOne("service_data.Models.EntityModels.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("service_data.Models.EntityModels.Ticket", null)
                        .WithMany("Messages")
                        .HasForeignKey("Ticket_id");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.Ticket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("service_data.Models.EntityModels.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
